services:
  - type: web
    name: notefusion-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
<<<<<<< HEAD
        sync: false  # Set to your backend URL in Render dashboard (e.g., https://notefusion-backend.onrender.com)
      - key: VITE_ENV
        value: production
      - key: VITE_FIREBASE_API_KEY
        sync: false  # Will be set in the Render dashboard
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false  # Will be set in the Render dashboard
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false  # Will be set in the Render dashboard
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false  # Will be set in the Render dashboard
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false  # Will be set in the Render dashboard
      - key: VITE_FIREBASE_APP_ID
        sync: false  # Will be set in the Render dashboard
=======
        sync: false  # Will be set in the Render dashboard
      - key: VITE_ENV
        value: production
>>>>>>> fc8ed2a6ee76667dd0759a129f0149acc56be76e
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'
<<<<<<< HEAD
    env: static
    plan: free
    autoDeploy: true
=======
>>>>>>> fc8ed2a6ee76667dd0759a129f0149acc56be76e
