services:
  - type: web
    name: notefusion-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false  # Will be set in the Render dashboard
      - key: VITE_ENV
        value: production
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'
