version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notefusion-backend
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DEBUG=true
      - DATABASE_URL=postgresql+asyncpg://notefusion:notefusion123@db:5432/notefusion
      - REDIS_URL=redis://:${REDIS_PASSWORD:-your-redis-password}@redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-jwt-secret-here}
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - UPLOAD_FOLDER=/app/uploads
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000
      - FRONTEND_URL=http://localhost:3000
      - EMAILS_ENABLED=false
      - SMTP_TLS=false
      - SMTP_PORT=1025
      - SMTP_HOST=localhost
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/v1/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
      args:
        - NODE_ENV=development
    container_name: notefusion-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network
      - frontend-network

  # Database Service
  db:
    image: postgres:13-alpine
    container_name: notefusion-db
    environment:
      - POSTGRES_USER=notefusion
      - POSTGRES_PASSWORD=notefusion123
      - POSTGRES_DB=notefusion
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notefusion -d notefusion"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  postgres_data:
