version: '3.8'

services:
  # Only start essential services
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DEBUG=true
      - DATABASE_URL=postgresql+asyncpg://notefusion:notefusion123@db:5432/notefusion
      - REDIS_URL=redis://:your-redis-password@redis:6379/0
      - SECRET_KEY=dev-secret-key
      - JWT_SECRET_KEY=dev-jwt-secret
      - EMAILS_ENABLED=true
      - SMTP_TLS=false
      - SMTP_PORT=1025
      - SMTP_HOST=mailhog
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api/v1

  # Only include essential supporting services
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: notefusion
      POSTGRES_PASSWORD: notefusion123
      POSTGRES_DB: notefusion
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notefusion -d notefusion"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass your-redis-password
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
