version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notefusion-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=development
      - DEBUG=true
      - DATABASE_URL=postgresql+asyncpg://notefusion:notefusion123@db:5432/notefusion
      - SECRET_KEY=your-secret-key-here
      - JWT_SECRET_KEY=your-jwt-secret-key-here
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000
    depends_on:
      - db

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notefusion-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  # Database Service
  db:
    image: postgres:13-alpine
    container_name: notefusion-db
    environment:
      - POSTGRES_USER=notefusion
      - POSTGRES_PASSWORD=notefusion123
      - POSTGRES_DB=notefusion
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notefusion -d notefusion"]
      interval: 5s
      timeout: 5s
      retries: 5

# Volumes
volumes:
  postgres_data:
