import sys
import os
from pathlib import Path

# Add the current directory to the Python path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

def test_video_service():
    print("Testing Video Generation Service")
    print("=" * 50)
    
    # Create necessary directories
    os.makedirs("app/videos", exist_ok=True)
    os.makedirs("app/temp", exist_ok=True)
    
    try:
        # Try to import the service
        from app.services.video.service import VideoGenerationService
        from app.schemas.video import VideoGenerationRequest, VideoStyle, VideoVoice
        from app.db.session import SessionLocal
        
        print("✅ All required modules imported successfully!")
        
        # Initialize database session
        db = SessionLocal()
        
        # Create test request
        request = VideoGenerationRequest(
            title="Test Video",
            description="This is a test video",
            script="""
            # Welcome to NoteFusion AI
            
            This is a test video generated by NoteFusion AI.
            """,
            style=VideoStyle.EDUCATIONAL,
            voice=VideoVoice.NEUTRAL,
            duration_per_slide=5,
            include_captions=True
        )
        
        # Initialize service
        service = VideoGenerationService(db)
        
        print("\n✅ Service initialized successfully!")
        print("\nNote: To test the actual video generation, run the FastAPI server and make a request to the /video/generate endpoint.")
        print("\nExample curl command:")
        print("""
curl -X 'POST' \
  'http://localhost:8000/api/v1/video/generate' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "title": "Test Video",
    "description": "This is a test video",
    "script": "# Welcome to NoteFusion AI\\n\\nThis is a test video generated by NoteFusion AI.",
    "style": "educational",
    "voice": "neutral",
    "duration_per_slide": 5,
    "include_captions": true
  }'
""")
        
    except ImportError as e:
        print(f"\n❌ Import error: {e}")
        print("\nPlease make sure you're running this from the backend directory and all dependencies are installed.")
    except Exception as e:
        print(f"\n❌ An error occurred: {e}")
    finally:
        if 'db' in locals():
            db.close()

if __name__ == "__main__":
    test_video_service()
