import os
import sys
import json
import requests
from pathlib import Path

# Add the parent directory to the path so we can import from app
sys.path.append(str(Path(__file__).parent.parent))

# Configuration
BASE_URL = "http://localhost:8000"  # Update this if your server is running on a different URL
TEST_VIDEO_PATH = "test_video.mp4"


def test_video_generation():
    """Test the /video/generate endpoint with a sample request."""
    url = f"{BASE_URL}/video/generate"
    
    # Sample request payload
    payload = {
        "text": "This is a test video generated by the NoteFusion AI system. "
                "This video demonstrates the video generation capability of the platform. "
                "The system can convert text into engaging video presentations with narration.",
        "voice": "female",
        "style": "Minimal"
    }
    
    print(f"Sending request to {url}")
    print(f"Payload: {json.dumps(payload, indent=2)}")
    
    try:
        # Send the request
        response = requests.post(url, json=payload, stream=True)
        
        # Check if the request was successful
        if response.status_code == 200:
            # Save the video file
            with open(TEST_VIDEO_PATH, 'wb') as f:
                for chunk in response.iter_content(chunk_size=8192):
                    f.write(chunk)
            
            print(f"✅ Success! Video saved to {TEST_VIDEO_PATH}")
            print(f"File size: {os.path.getsize(TEST_VIDEO_PATH) / (1024 * 1024):.2f} MB")
            return True
        else:
            print(f"❌ Request failed with status code {response.status_code}")
            print(f"Response: {response.text}")
            return False
            
    except Exception as e:
        print(f"❌ An error occurred: {str(e)}")
        return False


if __name__ == "__main__":
    print("=== Testing Video Generation Endpoint ===")
    success = test_video_generation()
    
    if success:
        print("✅ Test completed successfully!")
    else:
        print("❌ Test failed!")
        sys.exit(1)
