import React from 'react';
import { Link } from 'react-router-dom';
import {
  Sparkles,
  Brain,
  Zap,
  Mic,
  ScanLine,
  FileText,
  GitFork,
  BookOpen,
  Presentation,
  ShieldCheck,
  ArrowRight,
  CheckCircle2,
  Cpu,
  Globe,
  Layers,
  Star
} from 'lucide-react';
import './LandingPage.css';

const LandingPage: React.FC = () => {
  return (
    <div className="landing-container">
      <div className="landing-bg-glow-1"></div>
      <div className="landing-bg-glow-2"></div>

      {/* Navbar */}
      <header className="landing-navbar">
        <Link to="/" className="landing-logo">
          <div className="landing-logo-icon">
            <Brain className="w-5 h-5 text-white" />
          </div>
          <span>NoteFusion <span className="text-indigo-400">AI</span></span>
        </Link>

        <ul className="landing-nav-links">
          <li><a href="#features" className="landing-nav-link">Features</a></li>
          <li><a href="#solutions" className="landing-nav-link">Capabilities</a></li>
          <li><a href="#comparison" className="landing-nav-link">Why NoteFusion</a></li>
          <li><Link to="/playground" className="landing-nav-link">AI Playground</Link></li>
        </ul>

        <div className="landing-nav-actions">
          <Link to="/login" className="btn-landing-secondary">Log In</Link>
          <Link to="/dashboard" className="btn-landing-primary">
            Open App <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </header>

      {/* Hero Section */}
      <section className="landing-hero">
        <div className="landing-badge">
          <Sparkles className="w-4 h-4" /> Next-Gen AI Knowledge Engine 2.0
        </div>
        
        <h1 className="landing-hero-title">
          Transform Your Ideas into <br />
          <span className="landing-gradient-text">Neural Intelligence</span>
        </h1>
        
        <p className="landing-hero-subtitle">
          NoteFusion AI combines multimodal note-taking, active recall, knowledge graph visualization, 
          and specialized Socratic AI tutors into one seamless workspace.
        </p>

        <div className="landing-hero-ctas">
          <Link to="/dashboard" className="btn-landing-primary btn-hero-main">
            Get Started Free <ArrowRight className="w-5 h-5" />
          </Link>
          <Link to="/playground" className="btn-landing-secondary btn-hero-main">
            Try AI Playground
          </Link>
        </div>

        {/* Live Interactive App Preview */}
        <div className="landing-preview-frame">
          <div className="landing-preview-header">
            <div className="preview-dot dot-red"></div>
            <div className="preview-dot dot-yellow"></div>
            <div className="preview-dot dot-green"></div>
            <span className="text-xs text-gray-400 ml-2 font-mono">notefusion.ai/workspace/neural-synthesis</span>
          </div>

          <div className="landing-preview-body">
            <div className="preview-sidebar">
              <div className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-3">Workspace</div>
              <div className="preview-sidebar-item active">
                <Brain className="w-4 h-4 text-indigo-400" /> Neural Copilot
              </div>
              <div className="preview-sidebar-item">
                <FileText className="w-4 h-4 text-gray-400" /> Quantum Physics Notes
              </div>
              <div className="preview-sidebar-item">
                <Mic className="w-4 h-4 text-gray-400" /> Voice Transcriptions
              </div>
              <div className="preview-sidebar-item">
                <GitFork className="w-4 h-4 text-gray-400" /> Mind Maps & Graphs
              </div>
              <div className="preview-sidebar-item">
                <BookOpen className="w-4 h-4 text-gray-400" /> Spaced Repetition
              </div>
            </div>

            <div className="preview-main-content">
              <div className="flex items-center justify-between border-b border-gray-800 pb-3 mb-4">
                <div>
                  <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-indigo-400" /> Deep Learning Synthesis & Active Recall
                  </h3>
                  <span className="text-xs text-gray-400">Auto-generated by Socratic AI Engine</span>
                </div>
                <span className="px-2.5 py-1 rounded-full bg-indigo-500/20 text-indigo-300 text-xs font-semibold">
                  100% Free Access
                </span>
              </div>

              <div className="space-y-3 text-sm text-gray-300">
                <div className="p-3 rounded-lg bg-gray-800/60 border border-gray-700/50">
                  <div className="text-xs text-indigo-400 font-semibold mb-1">KEY TAKEAWAY</div>
                  NoteFusion automatically links conceptual blocks across documents using semantic vectors.
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div className="p-3 rounded-lg bg-indigo-900/30 border border-indigo-500/30">
                    <div className="font-semibold text-indigo-200 mb-1">Automated Quiz</div>
                    <p className="text-xs text-gray-400">3 flashcards created for review today.</p>
                  </div>
                  <div className="p-3 rounded-lg bg-purple-900/30 border border-purple-500/30">
                    <div className="font-semibold text-purple-200 mb-1">Knowledge Graph</div>
                    <p className="text-xs text-gray-400">14 interconnected concept nodes mapped.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Feature Grid Section */}
      <section id="features" className="landing-section">
        <div className="section-header">
          <span className="section-tag">Supercharged Features</span>
          <h2 className="section-title">Everything You Need to Master Any Subject</h2>
          <p className="section-subtitle">
            Engineered for students, researchers, creators, and professionals who demand speed and depth.
          </p>
        </div>

        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon-wrapper">
              <Brain />
            </div>
            <h3 className="feature-card-title">Neural Copilot & Socratic Tutor</h3>
            <p className="feature-card-desc">
              Engage with intelligent AI personas (Examiner, Architect, Socratic Tutor, Logic Debater) to test your reasoning and deepen retention.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-wrapper">
              <Mic />
            </div>
            <h3 className="feature-card-title">Multimodal Capture</h3>
            <p className="feature-card-desc">
              Capture ideas via Voice Notes, OCR Document Scanning, Web Clipper, and PDF Annotations with instant transcriptions.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-wrapper">
              <GitFork />
            </div>
            <h3 className="feature-card-title">Interactive Knowledge Graph</h3>
            <p className="feature-card-desc">
              Visualize connections between thoughts with 2D/3D Graph Views and Mind Maps that evolve as you add content.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-wrapper">
              <Zap />
            </div>
            <h3 className="feature-card-title">Spaced Repetition & Quiz Engine</h3>
            <p className="feature-card-desc">
              Auto-generate smart flashcards and adaptive quizzes optimized with SuperMemo algorithms for maximum memory retention.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-wrapper">
              <Presentation />
            </div>
            <h3 className="feature-card-title">Instant Slide & Doc Generator</h3>
            <p className="feature-card-desc">
              Convert raw notes into polished presentation slides, formatted markdown documents, or web-ready publications.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-wrapper">
              <ShieldCheck />
            </div>
            <h3 className="feature-card-title">Privacy-First Ecosystem</h3>
            <p className="feature-card-desc">
              Your data stays encrypted with export/backup controls, multi-language support, and full offline caching capabilities.
            </p>
          </div>
        </div>

        {/* Stats Banner */}
        <div id="comparison" className="stats-banner">
          <div>
            <div className="stat-number">100%</div>
            <div className="stat-label">Free & Unlocked Access</div>
          </div>
          <div>
            <div className="stat-number">10x</div>
            <div className="stat-label">Faster Knowledge Synthesis</div>
          </div>
          <div>
            <div className="stat-number">5+</div>
            <div className="stat-label">Specialized AI Tutors</div>
          </div>
          <div>
            <div className="stat-number">24/7</div>
            <div className="stat-label">Real-time Synchronization</div>
          </div>
        </div>
      </section>

      {/* CTA Box */}
      <section className="landing-section">
        <div className="landing-cta-box">
          <h2 className="cta-title">Ready to Upgrade Your Mind?</h2>
          <p className="cta-subtitle">
            Experience the full suite of NoteFusion AI tools — no subscriptions, no paywalls.
          </p>
          <Link to="/dashboard" className="btn-cta-white">
            Launch NoteFusion Workspace <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <div>
          © {new Date().getFullYear()} NoteFusion AI. All rights reserved.
        </div>
        <div className="flex items-center gap-6">
          <Link to="/dashboard" className="hover:text-indigo-400 transition-colors">Dashboard</Link>
          <Link to="/playground" className="hover:text-indigo-400 transition-colors">Playground</Link>
          <Link to="/notes" className="hover:text-indigo-400 transition-colors">Notes</Link>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
